apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: naysayer
  namespace: ddis-asteroid--naysayer
  labels:
    shard: internal
  annotations:
    haproxy.router.openshift.io/timeout: 180s
spec:
  host: www.cluster-url.com
  to:
    kind: Service
    name: naysayer
    weight: 100
  port:
    targetPort: https
  tls:
    termination: edge
  wildcardPolicy: None
